### ISSUE TITLE
improve example with UDPServer and client example code

### ISSUE THREAD

**Issue by ogonbat** [aiokitchen/aiomisc#70]
Hi ALl

would be possible to improve the example code with an UDPServer and client like the RPCServer?

Thanks in advance for your help

**Comment by ogonbat** [comment]
Great, thank you so much

In the merge i seen that you have updated the UDPServer Service, this was my doubt, was no sendto method or self.transport, anyway, if you dont update the version i will use the updated github code.
Thank you for your help

**Comment by mosquito** [comment]
The [aiomisc==10.0.8](https://pypi.org/project/aiomisc/10.0.8/) has been released.

**Comment by ogonbat** [comment]
Great work

thank you for your help
