### ISSUE TITLE
ERROR:aiomisc.periodic: Periodic task error:

### ISSUE THREAD

**Issue by kholmatov** [aiokitchen/aiomisc#72]
Я тут хочу запустить библиотеку **aioimaplib** через **aiomisc.service.periodic** но, при запуске получаю такой ответ:`RuntimeError: Event loop is closed` . 
Сам код нормально работает при запуске через **asyncio loop**. 
В чем могут быть проблемы?
**Log**: <img src="https://i.ibb.co/3F3CMzD/Screenshot-2020-05-29-at-19-35-14.png" />

**Comment by dizballanze** [comment]
Привет. По одному трейсбеку мало что понятно, но возможно, что ты не запускаешь сервис в entrypoint.
Можешь показать минимальный пример кода с такой проблемой?

**Comment by mosquito** [comment]
Возможно причина в том, что entrypoint создавая event loop закрывает уже созданный для этого потока так как для одного потока два экземпляра event loop ломают много прикладного кода. Если я прав, и ты создал PeriodicCallback с другим экземпляром event loop, то явная передача экземпляра event loop в entrypoint обойдет этупроблему ```with entrypoint(..., loop=asyncio.get_event_loop()): ...``` но так далать не очень хорошо. И да это только пои догадки и @dizballanze прав, нужен пример кода.

**Comment by kholmatov** [comment]
Привет, спасибо что, откликнулись все таки мне очень нравиться `aiomisc` в других моих проектах таких проблем не было :)
 
**Теперь к делу вот часть моего класса который я создал для PeriodicService:**
`class GrabberEmail(PeriodicService):

    async def load_mailbox(self, host, port, user, password, account_id):
        # у меня проблема тут возникает
        imap_client = aioimaplib.IMAP4_SSL(host=host,
                                           port=port,
                                           timeout=60 * 60 * 3)  
        await imap_client.wait_hello_from_server()
        status = await imap_client.login(user, password)
        if status.result == 'OK':
            await imap_client.select()
            result, uid_mail = await imap_client.uid_search('ALL')
            uid_list = uid_mail[0].split()
            # get_uid_not_in_db(uid_mail[0].split(), account_id)
            await self.load(imap_client, uid_list, account_id)

        await imap_client.logout()

    async def run_mailbox(self, account_id=1):
        path = os.getcwd()
        async with aiofiles.open(path + '/worker/config/.emails.json', 'r') as fp:
            for item in json.loads(await fp.read())['emails']:
                await self.load_mailbox(
                    item['imap'],
                    item['port'],
                    item['login'],
                    item['pass'],
                    account_id
                )

    async def callback(self):
        await self.run_mailbox()`

**Вот сам код которое запускает aiomisc.entrypoint:**

`if __name__ == '__main__':

    args = parse_args()
    services = [
        WebApi(
            address=args.address,
            port=args.port,
            static_url=args.static_url
        ),
        GrabberEmail(interval=args.interval)
    ]
    with aiomisc.entrypoint(*services) as loop:
        logging.info("Сервер запущен, на http://%s:%s",
                      args.address, args.port)
        loop.run_forever()`

**Comment by kholmatov** [comment]
Да я пробовал запустить вот так:
`with aiomisc.entrypoint(GrabberEmail(interval=args.interval)) as loop:
     loop.run_forever()`
пробела тот же

**Comment by kholmatov** [comment]
Ребята спасибо за ваши советы проблема решилась 
```
imap_client = aioimaplib.IMAP4_SSL(host=host,
                                           port=port,
                                           timeout=60,
                                           # вот тут отправляю текущий loop  <-------
                                           loop=asyncio.get_event_loop()
                                           )
```
