### ISSUE TITLE
Duplicated values under different keys in JSON Logger

### ISSUE THREAD

**Issue by vasiliykovalev** [aiokitchen/aiomisc#89]
Hi, thank you for great library!

What is the idea of writing the same values to the log under different keys, if we have already set new names for these fields?

1. This is mapping for keys: https://github.com/aiokitchen/aiomisc/blob/master/aiomisc/log/formatter/json.py#L31
2. Then we write under new names this keys: https://github.com/aiokitchen/aiomisc/blob/master/aiomisc/log/formatter/json.py#L68
3. Then later we iterate over all keys in record_dict https://github.com/aiokitchen/aiomisc/blob/master/aiomisc/log/formatter/json.py#L70, and write same values again under old key names.

Maybe we should iterate over `record_dict - FIELD_MAPPING.keys()`?

**Comment by mosquito** [comment]
Hmmm. Maybe that optimisation will be better. Do you want to contribute this? 

BTW: The logging helpers has not very well covered. Please try to make less changes as you can, it's really might help on the review.

**Comment by vasiliykovalev** [comment]
Add PR: https://github.com/aiokitchen/aiomisc/pull/90
